export const INSPIRATION_PROMPTS = [
  "Create a todo app with drag and drop functionality",
  "Build a weather dashboard with charts and forecasts",
  "Make a note-taking app with markdown support",
  "Create a chat application with real-time messaging",
  "Build a portfolio website with animations",
  "Make a recipe finder with ingredient search",
  "Create a habit tracker with streak counters",
  "Build a expense tracker with categories",
  "Make a quiz app with multiple choice questions",
  "Create a photo gallery with lightbox view",
  "Build a calendar app with event management",
  "Make a password generator with custom options",
  "Create a pomodoro timer with break reminders",
  "Build a color palette generator",
  "Make a QR code generator and scanner",
  "Create a URL shortener with analytics",
  "Build a text editor with syntax highlighting",
  "Make a file converter between different formats",
  "Create a barcode generator",
  "Build a random quote generator",
  "Make a unit converter for measurements",
  "Create a tip calculator",
  "Build a mortgage calculator",
  "Make a BMI calculator",
  "Create a age calculator",
  "Build a password strength checker",
  "Make a word counter and character counter",
  "Create a base64 encoder/decoder",
  "Build a JSON formatter and validator",
  "Make a markdown to HTML converter",
  "Create a Lorem ipsum generator",
  "Build a fake data generator",
  "Make a UUID generator",
  "Create a hash generator (MD5, SHA1, SHA256)",
  "Build a timestamp converter",
  "Make a color picker with hex, RGB, HSL",
  "Create a gradient generator",
  "Build a icon finder and downloader",
  "Make a font preview tool",
  "Create a image compressor",
  "Build a PDF merger and splitter",
  "Make a document scanner with OCR",
  "Create a voice recorder with playback",
  "Build a audio waveform visualizer",
  "Make a video player with controls",
  "Create a image editor with filters",
  "Build a meme generator",
  "Make a GIF creator from images",
  "Create a screen recorder",
  "Build a webcam capture tool"
];
